-- MySQL Script generated by MySQL Workbench
-- 10/31/15 22:16:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bug_bounty_server
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bug_bounty_server
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bug_bounty_server` DEFAULT CHARACTER SET utf8 ;
USE `bug_bounty_server` ;

-- -----------------------------------------------------
-- Table `bug_bounty_server`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_bounty_server`.`Account` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(20) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(16) NOT NULL COMMENT '',
  `dateCreated` DATETIME NOT NULL COMMENT '',
  `activated` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `dateDeactivated` DATETIME NULL DEFAULT NULL COMMENT '',
  `accountType` VARCHAR(10) NOT NULL COMMENT '',
  `dateOfLastActivity` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`userID`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_bounty_server`.`Marshall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_bounty_server`.`Marshall` (
  `marshallID` INT UNSIGNED NOT NULL COMMENT '',
  `rankingTotal` INT NOT NULL COMMENT '',
  `numRankings` INT NOT NULL COMMENT '',
  `rankingAvg` INT NOT NULL COMMENT '',
  `description` VARCHAR(200) NOT NULL COMMENT '',
  `imageLoc` VARCHAR(45) NOT NULL COMMENT '',
  `company` VARCHAR(25) NOT NULL COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`marshallID` ASC)  COMMENT '',
  PRIMARY KEY (`marshallID`)  COMMENT '',
  CONSTRAINT `fk_Sheriff_Account`
    FOREIGN KEY (`marshallID`)
    REFERENCES `bug_bounty_server`.`Account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_bounty_server`.`BountyPool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_bounty_server`.`BountyPool` (
  `poolID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `dateCreated` DATETIME NOT NULL COMMENT '',
  `payoutPool` VARCHAR(10) NOT NULL COMMENT '',
  `dateEnding` DATETIME NOT NULL COMMENT '',
  `bountyMarshallID` INT UNSIGNED NOT NULL COMMENT '',
  `bountyLink` VARCHAR(45) NOT NULL COMMENT '',
  `imageLoc` VARCHAR(45) NOT NULL COMMENT '',
  `lineDescription` TINYTEXT NULL DEFAULT NULL COMMENT '',
  `fullDescription` MEDIUMTEXT NULL DEFAULT NULL COMMENT '',
  `bountyName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`poolID`)  COMMENT '',
  UNIQUE INDEX `poolID_UNIQUE` (`poolID` ASC)  COMMENT '',
  INDEX `fk_BountyPool_Sheriff1_idx` (`bountyMarshallID` ASC)  COMMENT '',
  UNIQUE INDEX `bountyName_UNIQUE` (`bountyName` ASC)  COMMENT '',
  CONSTRAINT `fk_BountyPool_Sheriff1`
    FOREIGN KEY (`bountyMarshallID`)
    REFERENCES `bug_bounty_server`.`Marshall` (`marshallID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_bounty_server`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_bounty_server`.`Report` (
  `bountyID` INT UNSIGNED NOT NULL COMMENT '',
  `username` VARCHAR(20) NOT NULL COMMENT '',
  `reportText` MEDIUMTEXT NOT NULL COMMENT '',
  `dateSubmitted` DATETIME NOT NULL COMMENT '',
  `imageLoc` VARCHAR(100) NOT NULL COMMENT '',
  `reportID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`reportID`)  COMMENT '',
  UNIQUE INDEX `reportID_UNIQUE` (`reportID` ASC)  COMMENT '',
  CONSTRAINT `fk_Report_BountyPool2`
    FOREIGN KEY (`bountyID`)
    REFERENCES `bug_bounty_server`.`BountyPool` (`poolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Account1`
    FOREIGN KEY (`username`)
    REFERENCES `bug_bounty_server`.`Account` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_bounty_server`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_bounty_server`.`Message` (
  `messageID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `sender` INT UNSIGNED NOT NULL COMMENT '',
  `recipient` INT UNSIGNED NOT NULL COMMENT '',
  `messageText` LONGTEXT NOT NULL COMMENT '',
  `bountyID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`messageID`)  COMMENT '',
  UNIQUE INDEX `messageID_UNIQUE` (`messageID` ASC)  COMMENT '',
  UNIQUE INDEX `recipient_UNIQUE` (`recipient` ASC)  COMMENT '',
  UNIQUE INDEX `sender_UNIQUE` (`sender` ASC)  COMMENT '',
  UNIQUE INDEX `bountyID_UNIQUE` (`bountyID` ASC)  COMMENT '',
  CONSTRAINT `fk_Message_Account1`
    FOREIGN KEY (`sender`)
    REFERENCES `bug_bounty_server`.`Account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Account2`
    FOREIGN KEY (`recipient`)
    REFERENCES `bug_bounty_server`.`Account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_BountyPool1`
    FOREIGN KEY (`bountyID`)
    REFERENCES `bug_bounty_server`.`BountyPool` (`poolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_bounty_server`.`PreferredBounties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_bounty_server`.`PreferredBounties` (
  `bountyID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`bountyID`)  COMMENT '',
  UNIQUE INDEX `bountyID_UNIQUE` (`bountyID` ASC)  COMMENT '',
  CONSTRAINT `fk_PreferredBounties_BountyPool1`
    FOREIGN KEY (`bountyID`)
    REFERENCES `bug_bounty_server`.`BountyPool` (`poolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_bounty_server`.`unpaidReport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_bounty_server`.`unpaidReport` (
  `reportID` INT UNSIGNED NOT NULL COMMENT '',
  `dateAssessed` DATETIME NOT NULL COMMENT '',
  `message` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`reportID`)  COMMENT '',
  UNIQUE INDEX `reportID_UNIQUE` (`reportID` ASC)  COMMENT '',
  CONSTRAINT `fk_unpaidReport_Report1`
    FOREIGN KEY (`reportID`)
    REFERENCES `bug_bounty_server`.`Report` (`reportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_bounty_server`.`paidReport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_bounty_server`.`paidReport` (
  `reportID` INT UNSIGNED NOT NULL COMMENT '',
  `paidAmount` VARCHAR(10) NOT NULL COMMENT '',
  `datePaid` DATETIME NOT NULL COMMENT '',
  `message` MEDIUMTEXT NOT NULL COMMENT '',
  `publish` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`reportID`)  COMMENT '',
  UNIQUE INDEX `reportID_UNIQUE` (`reportID` ASC)  COMMENT '',
  CONSTRAINT `fk_paidReport_Report1`
    FOREIGN KEY (`reportID`)
    REFERENCES `bug_bounty_server`.`Report` (`bountyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
