-- MySQL Script generated by MySQL Workbench
-- 10/29/15 16:16:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BugBounty
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BugBounty
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BugBounty` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `BugBounty` ;

-- -----------------------------------------------------
-- Table `BugBounty`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`Account` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(20) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(16) NOT NULL COMMENT '',
  `dateCreated` DATETIME NOT NULL COMMENT '',
  `activated` TINYINT(1) NULL COMMENT '',
  `dateDeactivated` DATETIME NULL COMMENT '',
  `accountType` VARCHAR(10) NOT NULL COMMENT '',
  `loggedIn` TINYINT(1) NULL COMMENT '',
  `sessionCookie` BLOB NULL COMMENT '',
  `dateOfLastActivity` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`userID`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BugBounty`.`Marshall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`Marshall` (
  `marshallID` INT UNSIGNED NOT NULL COMMENT '',
  `rankingTotal` INT NOT NULL COMMENT '',
  `numRankings` INT NOT NULL COMMENT '',
  `rankingAvg` INT NOT NULL COMMENT '',
  `description` VARCHAR(200) NULL COMMENT '',
  `imageLoc` VARCHAR(45) NULL COMMENT '',
  `company` VARCHAR(25) NULL COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`marshallID` ASC)  COMMENT '',
  PRIMARY KEY (`marshallID`)  COMMENT '',
  CONSTRAINT `fk_Sheriff_Account`
    FOREIGN KEY (`marshallID`)
    REFERENCES `BugBounty`.`Account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BugBounty`.`BountyPool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`BountyPool` (
  `poolID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `dateCreated` DATETIME NOT NULL COMMENT '',
  `PayoutPool` INT NOT NULL COMMENT '',
  `dateEnding` DATETIME NOT NULL COMMENT '',
  `bountyMarshallID` INT UNSIGNED NOT NULL COMMENT '',
  `bountyLink` VARCHAR(45) NOT NULL COMMENT '',
  `imageLoc` VARCHAR(45) NULL COMMENT '',
  `lineDescription` TINYTEXT NULL COMMENT '',
  `fullDescription` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`poolID`)  COMMENT '',
  UNIQUE INDEX `poolID_UNIQUE` (`poolID` ASC)  COMMENT '',
  INDEX `fk_BountyPool_Sheriff1_idx` (`bountyMarshallID` ASC)  COMMENT '',
  UNIQUE INDEX `sheriffID_UNIQUE` (`bountyMarshallID` ASC)  COMMENT '',
  CONSTRAINT `fk_BountyPool_Sheriff1`
    FOREIGN KEY (`bountyMarshallID`)
    REFERENCES `BugBounty`.`Marshall` (`marshallID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BugBounty`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`Report` (
  `bountyID` INT UNSIGNED NOT NULL COMMENT '',
  `username` VARCHAR(20) NOT NULL COMMENT '',
  `ReportText` MEDIUMTEXT NULL COMMENT '',
  `payoutAmt` INT NOT NULL COMMENT '',
  `Assessed` TINYINT(1) NULL COMMENT '',
  `dateSubmitted` DATETIME NOT NULL COMMENT '',
  `dateLastAssessed` DATETIME NOT NULL COMMENT '',
  `ScreenshotFolderLoc` VARCHAR(100) NOT NULL COMMENT '',
  `Paid` TINYINT(1) NOT NULL COMMENT '',
  `reportID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `approved` TINYINT(1) NOT NULL COMMENT '',
  UNIQUE INDEX `hunterID_UNIQUE` (`username` ASC)  COMMENT '',
  PRIMARY KEY (`reportID`)  COMMENT '',
  UNIQUE INDEX `reportID_UNIQUE` (`reportID` ASC)  COMMENT '',
  UNIQUE INDEX `poolID_UNIQUE` (`bountyID` ASC)  COMMENT '',
  CONSTRAINT `fk_Report_BountyPool2`
    FOREIGN KEY (`bountyID`)
    REFERENCES `BugBounty`.`BountyPool` (`poolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Account1`
    FOREIGN KEY (`username`)
    REFERENCES `BugBounty`.`Account` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BugBounty`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`Message` (
  `messageID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `sender` INT UNSIGNED NOT NULL COMMENT '',
  `recipient` INT UNSIGNED NOT NULL COMMENT '',
  `messageText` LONGTEXT NULL COMMENT '',
  `bountyID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`messageID`)  COMMENT '',
  UNIQUE INDEX `messageID_UNIQUE` (`messageID` ASC)  COMMENT '',
  UNIQUE INDEX `recipient_UNIQUE` (`recipient` ASC)  COMMENT '',
  UNIQUE INDEX `sender_UNIQUE` (`sender` ASC)  COMMENT '',
  UNIQUE INDEX `bountyID_UNIQUE` (`bountyID` ASC)  COMMENT '',
  CONSTRAINT `fk_Message_Account1`
    FOREIGN KEY (`sender`)
    REFERENCES `BugBounty`.`Account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Account2`
    FOREIGN KEY (`recipient`)
    REFERENCES `BugBounty`.`Account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_BountyPool1`
    FOREIGN KEY (`bountyID`)
    REFERENCES `BugBounty`.`BountyPool` (`poolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BugBounty`.`ConfirmedBug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`ConfirmedBug` (
  `bugID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `poolID` INT UNSIGNED NOT NULL COMMENT '',
  `confirmationDate` DATETIME NOT NULL COMMENT '',
  `bugDesc` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`bugID`)  COMMENT '',
  UNIQUE INDEX `bugID_UNIQUE` (`bugID` ASC)  COMMENT '',
  INDEX `fk_ConfirmedBug_BountyPool1_idx` (`poolID` ASC)  COMMENT '',
  UNIQUE INDEX `poolID_UNIQUE` (`poolID` ASC)  COMMENT '',
  CONSTRAINT `fk_ConfirmedBug_BountyPool1`
    FOREIGN KEY (`poolID`)
    REFERENCES `BugBounty`.`BountyPool` (`poolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BugBounty`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`Review` (
  `reviewID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sheriffID` INT NOT NULL COMMENT '',
  `hunterID` INT NOT NULL COMMENT '',
  `reviewText` MEDIUMTEXT NOT NULL COMMENT '',
  PRIMARY KEY (`reviewID`)  COMMENT '',
  UNIQUE INDEX `reviewID_UNIQUE` (`reviewID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BugBounty`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`Subscription` (
  `subID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `subMarshallID` INT UNSIGNED NOT NULL COMMENT '',
  `subHunterID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`subID`)  COMMENT '',
  UNIQUE INDEX `subID_UNIQUE` (`subID` ASC)  COMMENT '',
  UNIQUE INDEX `sheriffID_UNIQUE` (`subMarshallID` ASC)  COMMENT '',
  UNIQUE INDEX `subHunterID_UNIQUE` (`subHunterID` ASC)  COMMENT '',
  CONSTRAINT `fk_Subscription_Sheriff1`
    FOREIGN KEY (`subMarshallID`)
    REFERENCES `BugBounty`.`Marshall` (`marshallID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscription_Account1`
    FOREIGN KEY (`subHunterID`)
    REFERENCES `BugBounty`.`Account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BugBounty`.`PreferredBounties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BugBounty`.`PreferredBounties` (
  `bountyID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`bountyID`)  COMMENT '',
  UNIQUE INDEX `bountyID_UNIQUE` (`bountyID` ASC)  COMMENT '',
  CONSTRAINT `fk_PreferredBounties_BountyPool1`
    FOREIGN KEY (`bountyID`)
    REFERENCES `BugBounty`.`BountyPool` (`poolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
